#!/usr/bin/env bash

#===================================================================================
#                          Import tools library
#===================================================================================
first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/../../singletons" # . "$(container-singletons --lib)"

#===================================================================================
#                              Logging Options
#===================================================================================
logging::set_severity info

#===================================================================================
#                              Help Message
#===================================================================================
showhelp() {
    local _synopsis="
        Maintain remote repo instances
    "

    local -A _keywords=(
        [debug]="Expose debug level logging"
        [info]="Expose normal level logging"
        [warning]="Expose error level logging"
        [error]="Expose error level logging"
        [fatal]="Expose fatal error level logging"
        [instance:]="Select the singleton container instance name"
        [remote:]="Select a remote image name"
        [commit]="Commit and push the instance"
        [version]="Produce the version string"
        [help]="Display instructions"
    )

    local _terms="$(echo "${@}" | awk -F, '{for (i=1; i <= NF; ++i) {print $i;}}')"
    local _topic

    local _contents="$(
        echo "${_terms}" | awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
        echo -en "${_synopsis:+\n}"
        echo "${_synopsis}" | sed -e 's/^[ ]*//g' -e '/^[ ]*$/d'

        echo "${_terms}" | {
            _prefix="\n"

            while read _topic
            do
                if [ -n "${_keywords["${_topic}"]}" ]
                then
                    _fill="$(for ((i=$(echo -n "${_topic}" | wc -c); i < 15; ++i)); do echo -n " "; done)"
                    echo -e "${_prefix}--${_topic}${_fill}${_keywords["${_topic}"]}" | sed -e 's/^./    &/g'
                    _prefix=""
                fi
            done
        }
    )"

    echo -e "Usage: $0 ${_contents}\n" >&2
}

#===================================================================================
#
#===================================================================================
is_git() {
    echo "$1" | egrep -q '(git[\@\:\.]|github)'
}

#===================================================================================
# NOTE: There is a bug in getopts where not specifying at least one short option
#       will cause the first non option parameter to be discarded. Here, we just
#       use -h (help)
#===================================================================================
long_options="help,version,debug,info,warning,error,fatal,instance:,remote:,commit"

OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")

if [ $? != 0 ]
then
    logging::fatal "Invalid command line options ${OPTION_TEMP}"
fi

eval set -- "$OPTION_TEMP"

#===================================================================================
#                       Process command line parameters
#
# NOTE: The command line parameters are available for scripts which
#       source this file.
#===================================================================================
instance_name=
remote_image=
image_name=
docker_image=
container_id=

while true
do
    case "$1" in
        --debug|--info|--warning|--error|--fatal)
            logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
            shift
            ;;

        --remote)
            logging::warning "Selecting (remote) image '${2}'"
            remote_image="${2}"
            shift 2
            ;;

        --commit)
            if [ -z "${instance_name}" ]
            then
                logging::error "No instance name supplied"
                exit $?
            elif [ -z "${remote_image}" ]
            then
                logging::error "No remote image supplied"
                exit $?
            elif ! image_name="$(singletons::instance::get_image_from_instance "${instance_name}")"
            then
                exit $?
            elif ! docker_image="$(singletons::instance::get_docker_image "${image_name}")"
            then
                logging::error "Cannot find docker image for ${image_name}"
                exit $?
            elif [ -z "${docker_image}" ]
            then
                logging::error "Cannot find docker image for ${image_name}"
                exit $?
            fi

            container_id="$(
                sudo docker ps -a --filter ancestor="${image_name}" --format "{{.ID}}"
            )"

            if [ -z "${container_id}" ]
            then
                logging::error "Cannot locate container for ${image_name}"
                exit $?
            fi

            logging::warning "Committing $instance_name to ${remote_image}"

            # e.g. pier:5000/dkw/riskpython3:development
            if ! sudo docker commit ${container_id} "${remote_image}"
            then
                exit $?
            elif ! sudo docker push "${remote_image}"
            then
                exit $?
            fi

            shift
            ;;

        --instance)
            logging::warning "Selecting instance '${2}'"
            instance_name="${2}"
            shift 2
            ;;

        --version)
            singletons::version
            exit 0
            ;;

        --)
            shift
            break
            ;;

        *)
            showhelp "${long_options}" >&2
            exit 0
            ;;
    esac
done